version: '3'
services:
  frontend:
    build: ./frontend  
    ports:
      - "5173:5173"
    depends_on:
      - backend  
  backend:
    build: ./backend 
    ports:
      - "8888:8888" 
    depends_on:
      - mongodb-server
  mongodb-server:
    image: mongo:latest  
    ports:
      - "27017:27017"  
