version: '3'
services:
  frontend:
    build: ./frontend  
    ports:
      - "5178:5173"
    depends_on:
      - backend  
  backend:
    build: ./backend 
    ports:
      - "3000:3000" 
    depends_on:
      - mongodb  

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
