version: '3'
services:
  frontend:
    image: ghcr.io/bosh-wang/bosh-wang/hw-frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - backend  
  backend:
    image: ghcr.io/bosh-wang/bosh-wang/hw-backend:latest
    ports:
      - "8888:8888" 
    depends_on:
      - mongodb-server
  mongodb-server:
    image: mongo:latest  
    ports:
      - "27017:27017"  
