name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push frontend Docker image
      run: |
        cd frontend
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-frontend:latest .
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-frontend:latest

    - name: Build and push backend Docker image
      run: |
        cd backend
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-backend:latest .
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-backend:latest

    - name: Deploy to GCP VM
      env:
        GCP_SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
        GCP_SSH_USER: wangbosh0604
        GCP_VM_IP: 35.239.136.96
      run: |
        echo "$GCP_SSH_KEY" > gcp_ssh_key
        chmod 600 gcp_ssh_key
        ssh -o StrictHostKeyChecking=no -i gcp_ssh_key $GCP_SSH_USER@$GCP_VM_IP << 'EOF'
          docker-compose down
          docker-compose up -d
        EOF
