name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: cd backend && npm install

    - name: Run tests
      run: cd backend && npm run test > ../coverage_check/output.txt

    - name: Compare coverage
      run: cd coverage_check && python coverage_check.py

    - name: Check coverage result
      if: steps.compare-coverage.outcome == 'failure'
      run: exit 1

    # - name: Format code
    #   id: format-code
    #   run: |
    #     git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -E '\.js$' | xargs npx prettier --write

    # - name: Commit formatted code
    #   if: steps.format-code.outputs.changed == 'true'
    #   run: |
    #     git config --global user.name 'github-actions'
    #     git config --global user.email 'github-actions@github.com'
    #     git add .
    #     git commit -m 'chore: format code with Prettier'
    #     git push